formatter: markdown document

settings:
  hide-empty: true
  lockfile: false

output:
  file: README.md

sort:
  enabled: true
  by: name

content: |-
  ## Usage

  ```hcl
  {{ include "examples/usage/main.tf" }}
  ```

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
